- python
    - python is programming paradigm means it support functional programming and object oriented  programming and also works with procedure oriented programming
- procedure oriented language
    - procedure oriented means write our programming language using functions,object and classes
- object oriented language
    - object:real word entity or its a physical entity
    - class:logical entity contains logic of a application

In [ ]:
# syntax for class
class class_name:
    variables
    methods or function

In [1]:
print("hai hello")

hai hello


In [2]:
3+8

11

In [7]:
class Hai:
    a=10
    b=20
    name="apssdc"
    def show():
        print("i am from show function")

In [8]:
Hai.name

'apssdc'

In [5]:
Hai.a

10

In [9]:
Hai.b

20

In [10]:
Hai.show()

i am from show function


In [11]:
print(Hai.a,Hai.b)

10 20


In [12]:
class Hi:
    name="apssdc"
    program_name="python"
    def display():
        print("i am from display function")
    def show():
        print("i am from show function")
print(Hi.name,Hi.program_name)
print(Hi.display())

apssdc python
i am from display function
None


In [15]:
print(Hi.display())

i am from display function
None


In [21]:
class Hello():
    def display():
        print("i am from display function")
        return("i am from return statement")
    def show():
        print("i am from show function()")
print(Hello.display())
print(Hello.show())

i am from display function
i am from return statement
i am from show function()
None


In [ ]:
# in java obj declaration:
 # clas_name obj_name=new_classname
# in python
 # obj_name=class_name

In [23]:
class Hi:
    name="apssdc"
    program_name="python"
    def display(self):
        print("i am from display function")
        return("i am from return statement")
    def show():
        print("i am from show function")
obj=Hi()
print(obj.name,Hi.program_name)
print(obj.display())

apssdc python
i am from display function
i am from return statement


## constructor
- constructor:without using object we call function
    - in java::class_name should be same as method name
    - in python::we will use one special method to define constructor
    - __init(self)__

In [4]:
class Hai:
    def __init__(self,name,roll_no):
        self.name=name
        self.roll_no=roll_no
        print("Hai",self.name)
    def display(self):
        print("your roll_no",self.roll_no)
obj=Hai('jyothika','21A85A0507')
obj.display()

Hai jyothika
your roll_no 21A85A0507


### inhertiance
- inherits something parent class to child class

In [ ]:
class A:
    #a,b=10,20
class B(A):
    # c,d=40,50
    

In [5]:
class A:
    a,b=10,20
    def msg():
        print("i am from class A")
class B(A):
    c,d=40,50
    def msg1():
        print("i am from class b")
obj=B
print(obj.c,obj.a)
obj.msg1()
obj.msg()
        

40 10
i am from class b
i am from class A


### python libraries for data science
- organizing,processing,analyzing the huge amount of data
- apply data visulization
- extracting the data from the source
- nearly 20 python libraries are there
#### Top
- numpy
- pandas
- matplotlib
#### numpy
- numpy::(num+py)means numerical data+python
- it is a fundamental package for scientific computing in package
- numpy is python library
- it is used to create multidimnsional arrays for fast operations
    - its dealing with mathematical,scientific statical data
- numpy contains a powerful n- dimensional array object,which in the form of rows and columns
- we can initialize numpy arrays from nested python lists

In [ ]:
# how to install numpy
- pip install numpy

In [1]:
# how to import and use numpy package
import numpy as np

In [2]:
# how to find the numpy version
np.__version__

'1.20.3'

In [3]:
# how to create numpy arrays
import numpy as np
a=np.array([1,2,3,4])# single dimensional array
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
a2=np.array([[2,3,4],[4,6,8]])
print(a2)
print(type(a2))

[[2 3 4]
 [4 6 8]]
<class 'numpy.ndarray'>


In [5]:
# to know the shape of the array
a2.shape

(2, 3)

In [6]:
li=[2,3,4,'j','y','o']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))

<class 'list'>
['2' '3' '4' 'j' 'y' 'o']
<class 'numpy.ndarray'>


In [7]:
ar=np.array([[1,2],[3,4],[5,6]])
print(ar)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
print(ar.dtype)


int32


In [9]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [10]:
print(b.shape)

(2, 2)


In [11]:
b.itemsize

4

In [12]:
b.ndim

2

In [13]:
# range
a=np.array(range(10))
print(a)
print(type(a))
print(a.shape)
print(a.size)
b=np.array(range(1,10,2))
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
[1 3 5 7 9]
1


In [14]:
# arange()-third party of numpy library
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a=np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [16]:
x=np.arange(10)
print(x.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [17]:
# reshape of array
a1=np.array([1,2,3,4,5,6,7,8])
print(a1.shape)
print("before reshape",a1)
print(a1.ndim)
a2=a1.reshape(4,2)
print("after reshape",a2)
print(a2.shape)
print(a2.ndim)


(8,)
before reshape [1 2 3 4 5 6 7 8]
1
after reshape [[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2


In [18]:
# resize of arrays(its modifies shape and array itself)
a1=np.array([1,2,3,4,5,6,7,8])
print(a1)
print(a1.shape)
a1.resize(3)
print(a1)
print(a1.shape)
a1.resize(2,4)
print(a1)
print(a1.shape)
a1.resize(3,3)
print(a1)
print(a1.shape)

[1 2 3 4 5 6 7 8]
(8,)
[1 2 3]
(3,)
[[1 2 3 0]
 [0 0 0 0]]
(2, 4)
[[1 2 3]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [19]:
# zero array
import numpy as np
a1=np.zeros(3)
a2=np.zeros((2,4),dtype='int64')
print(a1.dtype)
print(a2.dtype)
print(a1)
print(a2)

float64
int64
[0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]]


In [20]:
# one array
a2=np.ones(3,dtype="int64")
print(a2)
np.ones((6,5),dtype="int64")

[1 1 1]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [22]:
# full array-full(dimensions,specified number)
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [23]:
np.diag(a)

array([7, 7, 7])

In [24]:
np.full((3,9),500)

array([[500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500]])

In [25]:
# eye array 
np.eye(6,dtype="int64")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int64)

In [27]:
n=np.eye(5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.diag(n)

array([1., 1., 1., 1., 1.])

In [29]:
r=np.random.randint(1,10)
r

4

In [30]:
s=np.random.randint(1,19,12).reshape(3,4)
s

array([[ 6, 11, 11,  4],
       [ 4, 18,  6,  7],
       [ 5,  8,  4, 15]])

In [31]:
p=np.random.random((6)).reshape(2,3)
p

array([[0.47016736, 0.44038557, 0.75585343],
       [0.94362065, 0.68568228, 0.47743951]])

In [32]:
f=np.random.randn(2,3)
f

array([[ 0.51821381,  0.8355288 , -0.60643185],
       [ 0.62069655, -1.15327255,  0.32170572]])

In [33]:
a=np.random.randint(1,30,(10,3))
a

array([[ 5, 16, 26],
       [14, 27, 13],
       [18,  5, 29],
       [ 1, 13, 12],
       [15, 28, 29],
       [24, 10, 28],
       [14, 24, 24],
       [22, 24, 29],
       [ 6, 14,  6],
       [25,  6, 19]])

In [35]:
a[1:5]

array([[14, 27, 13],
       [18,  5, 29],
       [ 1, 13, 12],
       [15, 28, 29]])

In [36]:
a[2:,:2]

array([[18,  5],
       [ 1, 13],
       [15, 28],
       [24, 10],
       [14, 24],
       [22, 24],
       [ 6, 14],
       [25,  6]])

In [37]:
a>10

array([[False,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True, False],
       [ True, False,  True]])

In [38]:
a[a>10].sum()

487

In [39]:
a.max()

29

In [40]:
a.min()

1

In [41]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [43]:
print(a+b)
print("*************")
print(a-b)
print("_______________")
print(a*b)
print("$$$$$$$$$$$$$")
print(a%b)
print(np.max(a))
print(np.min(b))

[[10 12 14]
 [16 18 20]
 [22 24 26]]
*************
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
_______________
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]
$$$$$$$$$$$$$
[[0 1 2]
 [3 4 5]
 [6 7 8]]
8
10


In [44]:
# 0 to 15--->(3,5)
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [45]:
print(np.mean(a))

7.0


In [46]:
print(np.median(a))

7.0


In [47]:
b.dot(a)

array([[175, 208, 241, 274, 307],
       [220, 262, 304, 346, 388],
       [265, 316, 367, 418, 469]])

In [48]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
a+3

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17]])

In [50]:
a+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
np.log2(2)

1.0

In [52]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [53]:
np.exp(1)

2.718281828459045

In [54]:
np.sin(0)

0.0

In [55]:
np.sin(30)

-0.9880316240928618

In [56]:
np.tan(30)

-6.405331196646276

In [57]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',